name: Daily GitHub Grind Report

on:
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate report
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
        run: python scripts/github_grind_checker.py

      - name: Checkout reports branch
        uses: actions/checkout@v4
        with:
          ref: reports
          path: reports-branch

      - name: Copy report to reports branch folder
        run: |
          cp reports/*.md reports-branch/reports/

      - name: Commit and push report
        working-directory: reports-branch
        env:
          TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
        run: |
          git config --global user.name 'GeneralK1ng'
          git config --global user.email 'generak1ng0@gmail.com'
          git add reports/*.md
          git commit -m "📊 Daily report for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push https://$TOKEN@github.com/GeneralK1ng/Grind-Checker.git reports
