name: Daily GitHub Grind Report

on:
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Generate report
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
        run: python scripts/grind_report.py

      - name: Commit and push report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add reports/*.md
          git commit -m "📊 Daily report for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
